name: PR Actions
on:
  - pull_request_target
  
jobs:
  label:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
